In [1]:
import numpy as np

* 3주차 강의 연습

In [2]:
x1 = np.array([[5],[6],[7]])
x2 = np.array([[6],[7],[5]])

x1t = x1.T
x2t = x2.T

X = np.vstack([x1t, x2t])
X

array([[5, 6, 7],
       [6, 7, 5]])

In [3]:
Xh = np.hstack([x1t, x2t])
Xh

array([[5, 6, 7, 6, 7, 5]])

In [4]:
Xv = np.vstack([x1,x2])
Xv

array([[5],
       [6],
       [7],
       [6],
       [7],
       [5]])

* 연습용 행렬을 만들 경우

In [5]:
onevecs = np.ones((3,4))
onevecs

zevecs = np.zeros((2,4))
zevecs

# 차원을 괄호 안에 튜플 형태로 표현

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
x = np.arange(0,9,3)
x

# (시작, 미만, 원소 간 간격[기본 간격 : 1])

array([0, 3, 6])

In [7]:
y = np.linspace(2, 8, 3)
y

# (시작, 끝, 만들고 싶은 원소의 개수[균일한 간격])

array([2., 5., 8.])

In [8]:
d = np.random.rand(1,3)
d

# rand(m,n) -> mxn 행렬 생성 (0과 1 사이에서 균일한 분포 랜덤 숫자)
# 사칙연산으로 생성하고 싶은 숫자 범위 지정 가능

array([[0.18348927, 0.2078878 , 0.22168901]])

In [9]:
e = np.random.randn(3,4)
e

# pdf에서 (3,4) 행렬을 랜덤으로 생성
# 평균(+-), 분산(*/)

array([[ 1.1770649 , -0.25502111, -0.14981746,  0.6360459 ],
       [-0.02652473,  1.34682938, -0.81535719, -1.42352886],
       [-0.46685116,  1.63953852,  0.15639331,  0.55572579]])

* 4주차 강의

In [10]:
# 행렬곱

A = np.arange(0,6).reshape(2,3)
A

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
B = np.random.randn(3,4)
B

array([[ 0.86576043, -1.28983522,  1.68328971, -0.14631309],
       [ 0.21729119, -1.52402731,  0.10244413,  0.07880774],
       [-1.1727502 ,  0.10058624,  0.44941119,  0.14535485]])

In [12]:
np.matmul(A, B)
# 순서 중요(차원이 맞지 않으면 에러)
# 아래 두 가지도 같은 연산 결과를 보여주지만 matmul연산이 가장 빈번하게 사용    

array([[-2.12820921, -1.32285482,  1.0012665 ,  0.36951744],
       [-2.39730495, -9.46268369,  7.70670156,  0.60306592]])

In [13]:
np.dot(A, B)
# 벡터(행렬) 내적 연산
# matmul연산과 dot연산은 다른 알고리즘이지만 2차원 행렬을 연산할 때는 같은 결과를 보여준다.

array([[-2.12820921, -1.32285482,  1.0012665 ,  0.36951744],
       [-2.39730495, -9.46268369,  7.70670156,  0.60306592]])

In [14]:
A@B

array([[-2.12820921, -1.32285482,  1.0012665 ,  0.36951744],
       [-2.39730495, -9.46268369,  7.70670156,  0.60306592]])

In [15]:
# 내적 연습
a = np.linspace(0,6,4)
a

array([0., 2., 4., 6.])

In [16]:
b = np.ones((4,1))
b

array([[1.],
       [1.],
       [1.],
       [1.]])

In [17]:
np.matmul(a,b)

array([12.])

In [18]:
type(np.matmul(a,b))
# a와 b를 내적 했을 때, 결과깂이 scalar지만 return 값은 array

numpy.ndarray

In [19]:
a = np.linspace(0,6,4).reshape(1,4)
a

array([[0., 2., 4., 6.]])

In [20]:
np.matmul(a,b)

array([[12.]])

In [21]:
np.matmul(a,b).squeeze()
# squeeze 명령어를 사용해서 scalar값으로 만들 수 있음(0차원)

array(12.)

In [22]:
np.matmul(a,b)[0,0]
#array를 scalar 바꾸는 간단한 방법

12.0