# Python & numpy review

- 유용한 강좌
- [CS231 python tutorial 한글번역](http://aikorea.org/cs231n/python-numpy-tutorial/)
- 
[Scipy-lectures](https://scipy-lectures.org/)
    - [Numpy](https://scipy-lectures.org/intro/numpy/index.html)
    - [Operations](https://scipy-lectures.org/intro/numpy/operations.html)

In [59]:
import numpy as np
import torch

In [60]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [61]:
# np.array (기본 단위 개체) -> torch.tensor(torch에서 기본 단위 개체 / vector, 다차원)

b = torch.tensor([1,2,3])
print(b)
print(b.shape)
print(b.ndim)

tensor([1, 2, 3])
torch.Size([3])
1


In [68]:
# numpy -> tensor
c = torch.from_numpy(a)
print(c)
print(c.shape)

# tensor -> numpy
d = c.numpy()
print(d)

tensor([1, 2, 3], dtype=torch.int32)
torch.Size([3])
[1 2 3]


### Vector의 표기 단위 차이

* 수학에서 벡터의 기본 표기 단위
    - Column (열) vector로 표기하는 것이 관습임.
    - 예제
    \begin{align*}
        x = \begin{bmatrix}
        x_1\\
        x_2\\
        x_3
        \end{bmatrix} \in \mathbb{R}^{3\times 1}
    \end{align*}
* pytorch에서 벡터의 기본 단위
    - 다른 구조체와 메모리 구조상 Row (행) vector로 표기하는 것이 관습
    - 예
    
    
                                    `x = torch.tensor([1, 2, 3])`

In [32]:
d = torch.tensor([1,3,4])
print(d)
d.T

tensor([1, 3, 4])


tensor([1, 3, 4])

In [33]:
d1 = d.reshape(1,-1).T
d1

# 2-d 이상 부터 transpose 명령어 실행 가능

tensor([[1],
        [3],
        [4]])

#### Python에서 Matrix 생성하기

* 다음 $X\in \mathbb{R}^{2\times 3}$ 행렬을 고려합시다:
\begin{align*}
X = \begin{bmatrix}
5 & 6 & 8 \\
6 & 7 & 4 \\
\end{bmatrix}
\end{align*}

* $X$ 행렬의 각 column (열)을 $x^{(i)}\in \mathbb{R}^2$이라고 하겠습니다. 즉, 
\begin{align*}
X = \begin{bmatrix}
x^{(1)} & x^{(2)} & x^{(3)}
\end{bmatrix}
\end{align*}
과 같이 표현 됩니다. 더 자세하게 한번더 설명하자면
\begin{align*}
x^{(1)} = \begin{bmatrix}
5\\
6
\end{bmatrix}, \quad
x^{(2)} = \begin{bmatrix}
6\\
7
\end{bmatrix}, \quad
x^{(3)} = \begin{bmatrix}
8\\
4
\end{bmatrix}
\end{align*}

* list에서 생성
- indexing, slicing

In [36]:
X = torch.tensor([[5,6,8],[6,7,4]])
X

tensor([[5, 6, 8],
        [6, 7, 4]])

In [44]:
print(X[:,1])    # column을 슬라이싱을 할 경우 squeeze한 형태인 row로 돌려줌 (원래의 모양을 유지하기 위해 reshape명령어 시용)
print(X[:,1].reshape(-1,1))    

tensor([6, 7])
tensor([[6],
        [7]])


* Tensor Attributes
- `ndim`
- `shape`
- `dtype`
- `device`

In [45]:
a = torch.tensor([[12,3,4]])
a

tensor([[12,  3,  4]])

In [46]:
a.ndim

2

In [50]:
a.shape

torch.Size([1, 3])

In [53]:
a.dtype
# torch의 자제적인 데이터 타입 존재(ex> dtype = torch.float64)

torch.int64

In [54]:
a.device
# tensor는 gpu에 올리는 것이 가능하기 때문에 현재 tensor가 어떤 디바이스에 올라가있는지 확인하는 명령어 필요

device(type='cpu')

#### (중요) Python에서의 Vector 

* 1-D vector
    - row vector만 표현 가능
* 2-D vector
    - row, column vector 모두 표현 가능
* 어떤 방식을 사용해야하는가?
* vector 또는 행렬에 적용하는 함수에 return 방식을 알고 있어야함!!

#### (수학) 차원 확인 명령어
- $X\in\mathbb{R}^{3\times 1}$
- `X.shape`

In [77]:
X = torch.tensor([[1],[2],[3]]).reshape(3,1)

In [78]:
X

tensor([[1],
        [2],
        [3]])

In [79]:
X.shape

torch.Size([3, 1])

#### Matrix 연산자 I
- Transpose (전치) $X^T$
    - `x.T`
- `reshape`

In [82]:
X = torch.tensor([[1., 2., 3.],
       [4., 5., 6.]])
X

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [83]:
X.shape

torch.Size([2, 3])

In [84]:
X.T

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [85]:
X.reshape(3,2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [86]:
X.reshape(6)

tensor([1., 2., 3., 4., 5., 6.])

In [87]:
X.reshape(6,1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])

In [88]:
A = X.reshape(6,1)
A

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])

In [92]:
X
# reshape이나 T 명령어는 원래의 tensor를 변형시키지 않는다(복사해서 사용)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

#### Vector transpose 주의점
- (중요) transpose 연산자는 1D array는 변환하지 못한다!

In [98]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [99]:
a.T

tensor([1, 2, 3])

In [100]:
a.ndim

1

In [101]:
b = torch.tensor([[1,2,3]])

In [102]:
b.T

tensor([[1],
        [2],
        [3]])

In [105]:
a.reshape(3,1)

tensor([[1],
        [2],
        [3]])

* 다음 두개의 $x^{(i)}\in\mathbb{R}^3$ vector를 고려합시다:
\begin{align*}
x^{(1)} = \begin{bmatrix}
5\\
6\\
8
\end{bmatrix}, \quad
x^{(2)} = \begin{bmatrix}
6\\
7\\
5
\end{bmatrix}
\end{align*}
* $X$ 행렬의 각 row (행)을 $(x^{(i)})^T\in \mathbb{R}^{1\times 3}$이라고 하겠습니다. 즉, 
\begin{align*}
X = \begin{bmatrix}
(x^{(1)})^T \\
(x^{(2)})^T \\
\end{bmatrix}
\end{align*}
과 같이 표현 됩니다. 
* 즉 $X\in \mathbb{R}^{2\times 3}$ 는 다음과 같죠:
\begin{align*}
X = \begin{bmatrix}
5 & 6 & 8 \\
6 & 7 & 4 \\
\end{bmatrix}
\end{align*}



In [107]:
x1 = torch.tensor([[5], [6], [7]])
x2 = torch.tensor([[6], [7], [5]])
print('x1=', x1)
print('x2=', x2)

x1= tensor([[5],
        [6],
        [7]])
x2= tensor([[6],
        [7],
        [5]])


In [108]:
x2.shape

torch.Size([3, 1])

In [109]:
x1T = x1.T
x2T = x2.T
print('x1T=', x1T)
print('x2T=', x2T)

x1T= tensor([[5, 6, 7]])
x2T= tensor([[6, 7, 5]])


In [110]:
x1TT = x1.reshape(1,3)
x1TT

tensor([[5, 6, 7]])

* `vstack` (vertical (수직) stack (쌓다))

In [111]:
X = torch.vstack([x1.T, x2.T])
X

tensor([[5, 6, 7],
        [6, 7, 5]])

* `hstack` (horizontal (수평) stack (쌓다))

In [112]:
Xhstack = torch.hstack([x1T, x2T])
Xhstack

tensor([[5, 6, 7, 6, 7, 5]])

In [114]:
Xhstack2 = torch.hstack([x1, x2])
Xhstack2

tensor([[5, 6],
        [6, 7],
        [7, 5]])

* Sequential Generation
     - `ones`
     - `zeros`
     - `arange`
     - `linspace`

In [115]:
zvec = torch.zeros((1,3))
zvec

tensor([[0., 0., 0.]])

In [116]:
torch.arange(0,10,1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
for i in torch.arange(10):
    print(i)

tensor(0)
tensor(1)
tensor(2)
tensor(3)
tensor(4)
tensor(5)
tensor(6)
tensor(7)
tensor(8)
tensor(9)


In [119]:
torch.linspace(0,4,10)

tensor([0.0000, 0.4444, 0.8889, 1.3333, 1.7778, 2.2222, 2.6667, 3.1111, 3.5556,
        4.0000])

In [120]:
a.shape

torch.Size([3])

* Random Generation
- `torch.rand`

In [121]:
d = 2*torch.rand(1,10)-1
d

tensor([[-0.6224, -0.0924,  0.8918,  0.0648, -0.2058,  0.3350,  0.8571, -0.6596,
         -0.8924, -0.3227]])

* Gaussian (Normal) random generation
    - pdf
\begin{align*}
p(x) = \frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{(x-\mu)^2}{2\sigma^2}}
\end{align*}

    - 정규분포 mean=0, variance = 1 생성 명령어
`torch.randn` 


In [140]:
e = np.sqrt(3)*torch.randn(30,40)+2
e

tensor([[ 4.0034,  1.6381,  2.3205,  ..., -1.8374, -0.9544, -1.5040],
        [ 3.6394,  0.4175, -1.4507,  ...,  0.9502, -0.0170,  1.8947],
        [ 4.8396,  4.7742,  1.1392,  ...,  1.9357,  5.1077,  0.7750],
        ...,
        [ 3.3821,  2.5469,  0.9295,  ..., -0.2775,  1.8022,  3.2595],
        [ 1.4554,  3.1803,  0.4230,  ...,  6.0399,  0.7703,  3.9454],
        [ 0.0182,  2.0036, -0.5207,  ..., -0.9682,  0.8140, -0.0987]])

In [142]:
torch.mean(e)
# 행렬 전체의 평균

tensor(2.0397)

In [143]:
torch.var(e)
# 분산

tensor(3.2087)

In [146]:
torch.sqrt(torch.tensor([3]))

tensor([1.7321])

* 차원축소
* `squeeze()`

In [147]:
f = torch.tensor([[[1,2,3,4]]])

In [148]:
f.shape

torch.Size([1, 1, 4])

In [149]:
f.squeeze().shape

torch.Size([4])

* Matrix multiplication
    - `matmul`
    - Generate $A\in\mathbb{R}^{3\times 2}$, $a^{(i)}\in\mathbb{R}^{3}$
        \begin{align*}
            A = \begin{bmatrix}
                a^{(1)} & a^{(2)} & a^{(3)}  
            \end{bmatrix}
        \end{align*}
        - Example, 
            \begin{align*}
            a^{(1)} = \begin{bmatrix}
                3 \\
                4 \\
                5 \\
            \end{bmatrix}
        \end{align*}
    - Generate $B\in\mathbb{R}^{3\times 4}$
        \begin{align*}
            B = \begin{bmatrix}
                b^{(1)} & b^{(2)} & b^{(3)}  & b^{(4)}  
            \end{bmatrix}
        \end{align*}
    - $(a^{(1)})^T \cdot b^{(2)}$

In [153]:
A = torch.arange(0,6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [157]:
B = torch.randn(3,2)
B

tensor([[-0.5857, -1.4199],
        [-3.7232, -0.4598],
        [-1.1887, -0.2281]])

In [158]:
A+B

tensor([[-0.5857, -0.4199],
        [-1.7232,  2.5402],
        [ 2.8113,  4.7719]])

In [159]:
a1 = A[:, 0].reshape(3,1)
a1

tensor([[0],
        [2],
        [4]])

In [160]:
B

tensor([[-0.5857, -1.4199],
        [-3.7232, -0.4598],
        [-1.1887, -0.2281]])

In [161]:
b2 = B[:, 1].reshape(-1,1)
b2

tensor([[-1.4199],
        [-0.4598],
        [-0.2281]])

In [166]:
torch.matmul(a1.T, b2)
# torch 는 matmul 명령어를 사용할 때 casting 연산을 자동으로 적용하지 않음 

RuntimeError: expected scalar type Long but found Float

In [169]:
a1f = a1.type(torch.float32)

In [171]:
torch.matmul(a1f.T, b2)
# type 명령어도 원래의 행렬을 직접 변환하지 않기 때문에 다른 변수에 저장하여 사용

tensor([[-1.8317]])

* Matrix operations
    - sum(axis)

In [172]:
C = torch.randn(3,3)
C

tensor([[-0.0664, -0.6715,  1.8510],
        [-0.8034, -0.6647, -0.5162],
        [-0.0614, -0.1603,  0.0900]])

In [173]:
D = torch.randn(3,3)
D

tensor([[ 0.3706, -0.1881, -0.3587],
        [-0.6214, -0.1075,  1.5758],
        [ 0.7822, -1.2095, -0.2419]])

In [175]:
c1 = C[0,:]
d1 = D[0,:]

In [178]:
a = torch.tensor([1,2,3,4])
b = 2*torch.ones(4)
b

tensor([2., 2., 2., 2.])

In [179]:
a

tensor([1, 2, 3, 4])

In [180]:
c = a*b
c

tensor([2., 4., 6., 8.])

* `sum`

In [181]:
torch.sum(a*b)

tensor(20.)

In [182]:
b.reshape(-1,1).dtype

torch.float32

In [191]:
torch.matmul(a.type(torch.float32), b.reshape(-1,1))

tensor([20.])

In [229]:
A = torch.arange(3,11, 1).reshape(2,4)
A

tensor([[ 3,  4,  5,  6],
        [ 7,  8,  9, 10]])

In [240]:
asr = torch.sum(A, axis = 1).reshape(-1,1)
asr
# sum 함수도 size가 1이면 squeeze해서 출력(column을 유지하려면 reshape)

tensor([[18],
        [34]])

In [239]:
asc = torch.sum(A, axis = 0).reshape(1,-1)
asc

tensor([[10, 12, 14, 16]])

In [248]:
asum = torch.sum(A).reshape(-1,1)
asum

tensor([[52]])

In [241]:
amc = torch.mean(A.type(torch.float32), axis = 0).reshape(1,-1)
amc

tensor([[5., 6., 7., 8.]])

In [242]:
amr = torch.mean(A.type(torch.float32), axis = 1).reshape(-1,1)
amr

tensor([[4.5000],
        [8.5000]])

In [249]:
am = torch.mean(A.type(torch.float32)).reshape(-1,1)
am

tensor([[6.5000]])

In [244]:
apr = torch.prod(A.type(torch.float32), axis = 1).reshape(-1,1)
apr

tensor([[ 360.],
        [5040.]])

In [246]:
apc = torch.prod(A.type(torch.float32), axis = 0).reshape(1,-1)
apc

tensor([[21., 32., 45., 60.]])

In [250]:
ap = torch.prod(A.type(torch.float32)).reshape(1,-1)
ap

tensor([[1814400.]])

* Broadcasting

![This is the caption\label{mylabel}](https://scipy-lectures.org/_images/numpy_broadcasting.png)
https://scipy-lectures.org/_images/numpy_broadcasting.png

In [254]:
A = torch.randn(4,3)
A

tensor([[ 1.8078,  0.5979,  1.1191],
        [ 1.7888, -0.5271, -1.1118],
        [-1.0435,  0.0948,  0.5919],
        [ 1.4369, -0.3106,  0.6704]])

In [255]:
B= torch.ones((4,1))
B

tensor([[1.],
        [1.],
        [1.],
        [1.]])

In [256]:
A+B

tensor([[ 2.8078,  1.5979,  2.1191],
        [ 2.7888,  0.4729, -0.1118],
        [-0.0435,  1.0948,  1.5919],
        [ 2.4369,  0.6894,  1.6704]])