# Python & numpy review

- 유용한 강좌
- [CS231 python tutorial 한글번역](http://aikorea.org/cs231n/python-numpy-tutorial/)
- 
[Scipy-lectures](https://scipy-lectures.org/)
    - [Numpy](https://scipy-lectures.org/intro/numpy/index.html)
    - [Operations](https://scipy-lectures.org/intro/numpy/operations.html)

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

- List 와 indexing

In [3]:
A = [1, 'b', 'c']

In [4]:
B = [10,20,30,40,50,60]

In [5]:
B[3:6]

[40, 50, 60]

In [6]:
Blist = B[3:6]
Blist

[40, 50, 60]

In [7]:
B[3:6][1]

50

In [8]:
type(B[3:6])

list

* List in List

In [9]:
B = [1, 2, 'c', [1, 3, 4]]
B

[1, 2, 'c', [1, 3, 4]]

In [10]:
type(B[3])

list

In [11]:
B[3][1]

3

In [12]:
C = [[1,2,3,4], [3,[12,4,5,65],'c', 10], 'a']

In [13]:
C[1][1][3]+10


75

### Vector의 표기 단위 차이

* 수학에서 벡터의 기본 표기 단위
    - Column (열) vector로 표기하는 것이 관습임.
    - 예제
    \begin{align*}
        x = \begin{bmatrix}
        x_1\\
        x_2\\
        x_3
        \end{bmatrix} \in \mathbb{R}^{3\times 1}
    \end{align*}
* 코딩 (Python)에서 벡터의 기본 단위
    - 다른 구조체와 메모리 구조상 Row (행) vector로 표기하는 것이 관습
    - 예
    
    
                                    `x = np.array([1, 2, 3])`

In [14]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [15]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a[1][1]

5

#### Python에서 Matrix 생성하기

* 다음 $X\in \mathbb{R}^{2\times 3}$ 행렬을 고려합시다:
\begin{align*}
X = \begin{bmatrix}
5 & 6 & 8 \\
6 & 7 & 4 \\
\end{bmatrix}
\end{align*}

* $X$ 행렬의 각 column (열)을 $x^{(i)}\in \mathbb{R}^2$이라고 하겠습니다. 즉, 
\begin{align*}
X = \begin{bmatrix}
x^{(1)} & x^{(2)} & x^{(3)}
\end{bmatrix}
\end{align*}
과 같이 표현 됩니다. 더 자세하게 한번더 설명하자면
\begin{align*}
x^{(1)} = \begin{bmatrix}
5\\
6
\end{bmatrix}, \quad
x^{(2)} = \begin{bmatrix}
6\\
7
\end{bmatrix}, \quad
x^{(3)} = \begin{bmatrix}
8\\
4
\end{bmatrix}
\end{align*}

* list에서 생성
- indexing, slicing

In [17]:
xr1 = np.array([5, 6, 7])

In [18]:
xr1

array([5, 6, 7])

In [19]:
xr1 = np.array([[5, 6, 7]])
xr1

array([[5, 6, 7]])

In [20]:
x1 = np.array([[5], [6]])
x1

array([[5],
       [6]])

In [21]:
x1.ndim

2

In [22]:
X = np.array([[1.,2.,3.],[4.,5.,6.], [6.,7.,8.]])

In [23]:
X

array([[1., 2., 3.],
       [4., 5., 6.],
       [6., 7., 8.]])

* check dimension
- `ndim`

In [24]:
a = np.array([12,3,4])

In [25]:
a.ndim

1

In [26]:
X.ndim

2

In [27]:
a = np.array([12,3,4])

In [28]:
b = np.array([[12,3,4]])

In [29]:
a.ndim

1

In [30]:
b.ndim

2

* check type
- `dtype`

In [31]:
X.dtype

dtype('float64')

In [32]:
type(X)

numpy.ndarray

In [33]:
y = np.array([[5],[6]])

In [34]:
y

array([[5],
       [6]])

#### (중요) Python에서의 Vector 

* 1-D vector
    - row vector만 표현 가능
* 2-D vector
    - row, column vector 모두 표현 가능
* 어떤 방식을 사용해야하는가?
* vector 또는 행렬에 적용하는 함수에 return 방식을 알고 있어야함!!

#### (수학) 차원 확인 명령어
- $X\in\mathbb{R}^{3\times 1}$
- `X.shape`

In [35]:
X = np.array([[1],[2],[3]])

In [36]:
X

array([[1],
       [2],
       [3]])

In [37]:
X.shape

(3, 1)

In [38]:
Y = np.array([[1,2,3],[4,5,6]])

In [39]:
Y.shape

(2, 3)

In [40]:
Y.ndim

2

#### Matrix 연산자 I
- Transpose (전치) $X^T$
    - `x.T`
- `reshape`

In [41]:
X = np.array([[1., 2., 3.],
       [4., 5., 6.]])
X

array([[1., 2., 3.],
       [4., 5., 6.]])

In [42]:
X.shape

(2, 3)

In [43]:
X.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [44]:
X.reshape(3,2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [45]:
X.reshape(6)

array([1., 2., 3., 4., 5., 6.])

In [46]:
X.reshape(6,1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [47]:
A = X.reshape(6,1)
A

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [48]:
X

array([[1., 2., 3.],
       [4., 5., 6.]])

#### Vector transpose 주의점
- (중요) transpose 연산자는 1D array는 변환하지 못한다!

In [49]:
a = np.array([1,2,3])

In [50]:
a.T

array([1, 2, 3])

In [51]:
a.shape

(3,)

In [52]:
b = np.array([[1,2,3]])

In [53]:
b.T

array([[1],
       [2],
       [3]])

In [54]:
#reshape 명령어로 차원 변경 가능
a.reshape(3,1)

array([[1],
       [2],
       [3]])

* 다음 두개의 $x^{(i)}\in\mathbb{R}^3$ vector를 고려합시다:
\begin{align*}
x^{(1)} = \begin{bmatrix}
5\\
6\\
8
\end{bmatrix}, \quad
x^{(2)} = \begin{bmatrix}
6\\
7\\
5
\end{bmatrix}
\end{align*}
* $X$ 행렬의 각 row (행)을 $(x^{(i)})^T\in \mathbb{R}^{1\times 3}$이라고 하겠습니다. 즉, 
\begin{align*}
X = \begin{bmatrix}
(x^{(1)})^T \\
(x^{(2)})^T \\
\end{bmatrix}
\end{align*}
과 같이 표현 됩니다. 
* 즉 $X\in \mathbb{R}^{2\times 3}$ 는 다음과 같죠:
\begin{align*}
X = \begin{bmatrix}
5 & 6 & 8 \\
6 & 7 & 4 \\
\end{bmatrix}
\end{align*}



In [55]:
x1 = np.array([[5], [6], [7]])
x2 = np.array([[6], [7], [5]])
print('x1=', x1)
print('x2=', x2)

x1= [[5]
 [6]
 [7]]
x2= [[6]
 [7]
 [5]]


In [56]:
x2.shape

(3, 1)

In [57]:
x1T = x1.T
x2T = x2.T
print('x1T=', x1T)
print('x2T=', x2T)

x1T= [[5 6 7]]
x2T= [[6 7 5]]


In [58]:
x1TT = x1.reshape(1,3)
x1TT

array([[5, 6, 7]])

* `vstack` (vertical (수직) stack (쌓다))

In [59]:
X = np.vstack([x1.T, x2.T])
X

array([[5, 6, 7],
       [6, 7, 5]])

* `hstack` (horizontal (수평) stack (쌓다))

In [60]:
Xhstack = np.hstack([x1T, x2T])
Xhstack

array([[5, 6, 7, 6, 7, 5]])

In [61]:
Xhstack2 = np.hstack([x1, x2])
Xhstack2

array([[5, 6],
       [6, 7],
       [7, 5]])

* Sequential Generation
     - `ones`
     - `zeros`
     - `arange`
     - `linspace`

In [62]:
zvec = np.zeros((1,3))
zvec

array([[0., 0., 0.]])

In [63]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
for i in np.arange(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [65]:
np.linspace(0,4,2)

array([0., 4.])

* Random Generation
- `random.rand`

In [66]:
d = 2*np.random.rand(1,10)-1
d

array([[ 0.07360147,  0.22873351,  0.4610341 ,  0.40608192, -0.81358473,
        -0.11074609,  0.66985177, -0.62555149,  0.83030637,  0.68691511]])

* Gaussian (Normal) random generation
    - pdf
\begin{align*}
p(x) = \frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{(x-\mu)^2}{2\sigma^2}}
\end{align*}

    - 정규분포 mean=0, variance = 1 생성 명령어
`numpy.random.randn` 


In [67]:
e = 2*np.random.randn(3,4)+2

In [68]:
e

array([[ 1.39645885,  2.23352855,  1.28058586,  1.35364408],
       [ 3.36000821,  1.0749352 ,  0.0974803 , -2.0313642 ],
       [ 2.0059158 ,  0.62390797, -0.08084242,  2.92670966]])

* 차원축소
* `squeeze()`

In [69]:
f = np.array([[[1,2,3,4]]])

In [70]:
f.shape

(1, 1, 4)

In [71]:
f.squeeze().shape

(4,)

* Matrix multiplication
    - `matmul`
    - Generate $A\in\mathbb{R}^{3\times 2}$, $a^{(i)}\in\mathbb{R}^{3}$
        \begin{align*}
            A = \begin{bmatrix}
                a^{(1)} & a^{(2)}
            \end{bmatrix}
        \end{align*}
        - Example, 
            \begin{align*}
            a^{(1)} = \begin{bmatrix}
                3 \\
                4 \\
                5 \\
            \end{bmatrix}
        \end{align*}
    - Generate $B\in\mathbb{R}^{3\times 4}$
        \begin{align*}
            B = \begin{bmatrix}
                b^{(1)} & b^{(2)} & b^{(3)}  & b^{(4)}  
            \end{bmatrix}
        \end{align*}
    - $(a^{(1)})^T \cdot b^{(2)}$

In [72]:
A = np.arange(0,6).reshape(3,2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [73]:
B = np.random.randn(3,4)
B

array([[-0.40483939, -1.85684455, -1.03391146,  0.15508108],
       [-0.30939575, -0.26798684, -1.31882229, -0.04776097],
       [-1.22511522, -0.85598752,  0.1052104 ,  0.57968991]])

In [90]:
A[:,0]
# 리스트 형태로 슬라이싱하면 column이 아닌 row 벡터로 리턴됨 (자동 squeeze)

array([0, 2, 4])

In [88]:
a1 = A[:, 0].reshape(3,1)
a1

array([[0],
       [2],
       [4]])

In [91]:
B

array([[-0.40483939, -1.85684455, -1.03391146,  0.15508108],
       [-0.30939575, -0.26798684, -1.31882229, -0.04776097],
       [-1.22511522, -0.85598752,  0.1052104 ,  0.57968991]])

In [93]:
b2 = B[:, 1].reshape(-1,1)
b2

array([[-1.85684455],
       [-0.26798684],
       [-0.85598752]])

In [97]:
np.matmul(a1.T, b2)

array([[-3.95992376]])

* Matrix operations
    - sum(axis)

In [112]:
C = np.random.randn(3,3)
C

array([[ 3.58622597e-01,  1.20837737e-03,  3.52665317e-01],
       [ 2.47250715e-01, -7.09818058e-01,  1.35229617e+00],
       [ 6.14398230e-01,  1.02146543e+00, -7.24444483e-01]])

In [113]:
D = np.random.randn(3,3)
D

array([[ 0.20267028, -1.11170213,  0.0848764 ],
       [ 0.35187029, -0.51776398,  0.10925881],
       [ 0.24376462, -1.58728543, -0.29205359]])

In [114]:
C+D

array([[ 0.56129288, -1.11049375,  0.43754172],
       [ 0.599121  , -1.22758203,  1.46155499],
       [ 0.85816285, -0.56582   , -1.01649807]])

In [117]:
c1 = C[0,:]
d1 = D[0,:]

In [118]:
c1 + d1

array([ 0.56129288, -1.11049375,  0.43754172])

In [120]:
a = np.array([1,2,3,4])
b = 2*np.ones(4)

In [124]:
print('a = ', a)
print('b = ', b)

a =  [1 2 3 4]
b =  [2. 2. 2. 2.]


In [130]:
c = a * b
d = a + b
print('c = ', c)
print('d = ', d)

c =  [2. 4. 6. 8.]
d =  [3. 4. 5. 6.]


* `sum`

In [139]:
np.sum(c)
# 원소들끼리의 곱인 c의 원소를 다 더한 값(matmul과 같아짐)

20.0

In [137]:
np.matmul(a, b.reshape(-1,1))

array([20.])

In [145]:
A = np.arange(3,11, 1).reshape(2,4)
A

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [156]:
c = np.sum(A, axis = 1).reshape(-1,1)
c
# 각 row끼리 더한 값 출력
# reshape 해주지 않으면 squeeze한 형태인 1d 로 출력

array([[18],
       [34]])

In [154]:
d = np.sum(A, axis = 0)
d
# 각 column끼리 더한 값 출력

array([10, 12, 14, 16])

In [158]:
A = np.random.randn(4,3)
A

array([[ 1.07960128, -2.2500569 , -0.23803936],
       [ 0.6677041 , -0.64259234,  0.13385159],
       [-0.29811215, -0.53317369,  1.05886698],
       [-1.55406938, -0.39158936,  1.8805332 ]])

In [159]:
B= np.ones((4,1))
B

array([[1.],
       [1.],
       [1.],
       [1.]])

In [161]:
A+B
# 행렬의 차원을 맞추거나, for문을 사용할 필요 없이 B(열)벡터를 A행렬의 각 열마다 더해줌 

array([[ 2.07960128, -1.2500569 ,  0.76196064],
       [ 1.6677041 ,  0.35740766,  1.13385159],
       [ 0.70188785,  0.46682631,  2.05886698],
       [-0.55406938,  0.60841064,  2.8805332 ]])

* Broadcasting

![This is the caption\label{mylabel}](https://scipy-lectures.org/_images/numpy_broadcasting.png)
https://scipy-lectures.org/_images/numpy_broadcasting.png

In [170]:
A1 = np.linspace(0,30,4).reshape(4,1)
A1

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [172]:
B2 = np.linspace(0,2,3)
B2

array([0., 1., 2.])

In [174]:
A1 + B2

array([[ 0.,  1.,  2.],
       [10., 11., 12.],
       [20., 21., 22.],
       [30., 31., 32.]])

In [175]:
A1 * B2

array([[ 0.,  0.,  0.],
       [ 0., 10., 20.],
       [ 0., 20., 40.],
       [ 0., 30., 60.]])